services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  DigitalMarketingFramework\Typo3\Distributor\Core\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  # REST API
  DigitalMarketingFramework\Typo3\Distributor\Core\Api\EventListener\ApiRouteResolversUpdateEventListener:
      tags:
          - name: event.listener
            event: DigitalMarketingFramework\Typo3\Core\Api\Event\ApiRouteResolversUpdateEvent

  # backend module controllers
  DigitalMarketingFramework\Typo3\Distributor\Core\Controller\EventListener\BackendControllerUpdateEventListener:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Core\Controller\Event\BackendControllerUpdateEvent

  # configuration document meta data update listeners
  DigitalMarketingFramework\Typo3\Distributor\Core\ConfigurationDocument\EventListener\ConfigurationDocumentMetaDataUpdateEventListener:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Core\ConfigurationDocument\Event\ConfigurationDocumentMetaDataUpdateEvent

  # registry update listeners
  DigitalMarketingFramework\Typo3\Distributor\Core\Registry\EventListener\CoreRegistryUpdateEventListener:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Core\Registry\Event\CoreRegistryUpdateEvent

  DigitalMarketingFramework\Typo3\Distributor\Core\Registry\EventListener\DistributorRegistryUpdateEventListener:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Distributor\Core\Registry\Event\DistributorRegistryUpdateEvent

  # frontend scripts updates
  DigitalMarketingFramework\Typo3\Distributor\Core\Api\EventListener\FrontendJavaScriptUpdateEventListener:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Core\Api\Event\FrontendJavaScriptUpdateEvent

  # frontend js settings build listeners
  DigitalMarketingFramework\Typo3\Distributor\Core\Api\EventListener\FrontendJavaScriptSettingsUpdateEventListener:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Core\Api\Event\FrontendJavaScriptSettingsUpdateEvent

  # sysext:form element processors
  DigitalMarketingFramework\Typo3\Distributor\Core\Extensions\Form\ElementProcessor\AbstractSectionElementProcessor:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Distributor\Core\Extensions\Form\FormElementProcessorEvent

  DigitalMarketingFramework\Typo3\Distributor\Core\Extensions\Form\ElementProcessor\ContentElementProcessor:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Distributor\Core\Extensions\Form\FormElementProcessorEvent

  DigitalMarketingFramework\Typo3\Distributor\Core\Extensions\Form\ElementProcessor\DateElementProcessor:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Distributor\Core\Extensions\Form\FormElementProcessorEvent

  DigitalMarketingFramework\Typo3\Distributor\Core\Extensions\Form\ElementProcessor\DatePickerElementProcessor:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Distributor\Core\Extensions\Form\FormElementProcessorEvent

  DigitalMarketingFramework\Typo3\Distributor\Core\Extensions\Form\ElementProcessor\FileUploadElementProcessor:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Distributor\Core\Extensions\Form\FormElementProcessorEvent

  DigitalMarketingFramework\Typo3\Distributor\Core\Extensions\Form\ElementProcessor\GenericElementProcessor:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Distributor\Core\Extensions\Form\FormElementProcessorEvent

  DigitalMarketingFramework\Typo3\Distributor\Core\Extensions\Form\ElementProcessor\HoneypotElementProcessor:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Distributor\Core\Extensions\Form\FormElementProcessorEvent

  DigitalMarketingFramework\Typo3\Distributor\Core\Extensions\Form\ElementProcessor\StaticTextElementProcessor:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Distributor\Core\Extensions\Form\FormElementProcessorEvent
