services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  DigitalMarketingFramework\Typo3\Distributor\Core\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  # registry collection
  DigitalMarketingFramework\Typo3\Distributor\Core\Registry\EventListener\RegistryCollectionEventListener:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Core\Registry\RegistryCollection

  # registry
  DigitalMarketingFramework\Typo3\Distributor\Core\Registry\EventListener\CoreRegistryUpdateEventListener:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Core\Registry\Event\CoreRegistryUpdateEvent

  DigitalMarketingFramework\Typo3\Distributor\Core\Registry\EventListener\DistributorRegistryUpdateEventListener:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Distributor\Core\Registry\Event\DistributorRegistryUpdateEvent

  # backend module controllers
  DigitalMarketingFramework\Typo3\Distributor\Core\Controller\EventListener\BackendControllerUpdateEventListener:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Core\Controller\Event\BackendControllerUpdateEvent

  # sysext:form events
  DigitalMarketingFramework\Typo3\Distributor\Core\Extensions\Form\EventListener\DataStructureIdentifierListener:
    tags:
      - name: event.listener
        after: 'form-framework/modify-data-structure'
        method: 'modifyDataStructure'

  # sysext:form element processors
  DigitalMarketingFramework\Typo3\Distributor\Core\Extensions\Form\ElementProcessor\AbstractSectionElementProcessor:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Distributor\Core\Extensions\Form\FormElementProcessorEvent

  DigitalMarketingFramework\Typo3\Distributor\Core\Extensions\Form\ElementProcessor\ContentElementProcessor:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Distributor\Core\Extensions\Form\FormElementProcessorEvent

  DigitalMarketingFramework\Typo3\Distributor\Core\Extensions\Form\ElementProcessor\DateElementProcessor:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Distributor\Core\Extensions\Form\FormElementProcessorEvent

  DigitalMarketingFramework\Typo3\Distributor\Core\Extensions\Form\ElementProcessor\DatePickerElementProcessor:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Distributor\Core\Extensions\Form\FormElementProcessorEvent

  DigitalMarketingFramework\Typo3\Distributor\Core\Extensions\Form\ElementProcessor\FileUploadElementProcessor:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Distributor\Core\Extensions\Form\FormElementProcessorEvent

  DigitalMarketingFramework\Typo3\Distributor\Core\Extensions\Form\ElementProcessor\GenericElementProcessor:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Distributor\Core\Extensions\Form\FormElementProcessorEvent

  DigitalMarketingFramework\Typo3\Distributor\Core\Extensions\Form\ElementProcessor\HoneypotElementProcessor:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Distributor\Core\Extensions\Form\FormElementProcessorEvent

  DigitalMarketingFramework\Typo3\Distributor\Core\Extensions\Form\ElementProcessor\StaticTextElementProcessor:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Distributor\Core\Extensions\Form\FormElementProcessorEvent
